        var data = {
            'settings': {
                'numberOfPlayers': '5',
                'pointValue': '0.10'
            },
            'players': {
                'player1': 'Steve',
                'player2': 'Marcus',
                'player3': 'Rob',
                'player4': 'James',
                'player5': 'Kelvin'
            },
            'scores': [{
                'id': '1',
                'player1': '1',
                'player2': '2',
                'player3': '3',
                'player4': '4',
                'player5': '5',
                'startTime': '2016-07-12T03:25:43.071Z'
            }, {
                'id': '2',
                'player1': '1',
                'player2': '2',
                'player3': '3',
                'player4': '4',
                'player5': '5',
                'startTime': '2016-07-12T03:25:43.071Z'
            }, {
                'id': '3',
                'player1': '1',
                'player2': '2',
                'player3': '3',
                'player4': '4',
                'player5': '5',
                'startTime': '2016-07-12T03:25:43.071Z'
            }, {
                'id': '4',
                'player1': '1',
                'player2': '2',
                'player3': '3',
                'player4': '4',
                'player5': '5',
                'startTime': '2016-07-12T03:25:43.071Z'
            }, {
                'id': '5',
                'player1': '1',
                'player2': '2',
                'player3': '3',
                'player4': '4',
                'player5': '5',
                'startTime': '2016-07-12T03:25:43.071Z'
            }, {
                'id': '6',
                'player1': '',
                'player2': '',
                'player3': '',
                'player4': '',
                'player5': '',
                'startTime': '2016-07-12T03:25:43.071Z'
            }]
        };